// app/layout.tsx or your RootLayout file
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/containers/header";  // Import the Header component
import { AuthProvider } from "@/containers/authContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#E7E4F1]`}>
          {/* Include Header as part of the layout */}
          <Header />
          {children}
      </body>
    </html>
  );
}
